name: prac_cam
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  geocoding: ^3.0.0
  location: ^7.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  